---
- name: "Setting hostname"
  hostname:
    name: "{{ hostname }}"
    use: systemd

- name: "Copying over bashrc"
  copy:
    src: bashrc
    dest: "~/.bashrc"
  become: true
  become_user: "{{ user }}"

- name: "Copying over banner image"
  copy:
    src: banner.image
    dest: "~/banner.image"
  become: true
  become_user: "{{ user }}"
